{{- $h2DatabaseIsUsed := eq (include "operaton-bpm.h2DatabaseIsUsed" .) "true" -}}
{{- $noCredentialsSecretIsProvided := (empty .Values.database.credentialsSecretName) -}}
{{- if and $h2DatabaseIsUsed $noCredentialsSecretIsProvided .Values.database.credentialsSecretEnabled -}}
# This secret is used for ephemeral H2 database only.
# Create your own secret for external databases like PostgreSQL.
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "operaton-bpm.fullname" . }}
  labels:
    {{- include "operaton-bpm.labels" . | nindent 4 }}
stringData:
  DB_PASSWORD: "sa"
  DB_USERNAME: "sa"
{{- end }}
