name: Lint, Test and Release Charts

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  HELM_VERSION: 3.17.0
  PYTHON_VERSION: 3.13

jobs:
  lint-chart:
    name: Lint chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: "${{ env.HELM_VERSION }}"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config .github/config/chart-testing.yaml --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --config .github/config/chart-testing.yaml

  test-install-chart:
    name: Test chart installation on K8s
    runs-on: ubuntu-latest
    needs:
      - lint-chart
    strategy:
      matrix:
        # see https://kubernetes.io/releases/patch-releases/#support-period
        k8s:
          - v1.32.2
          - v1.31.6
          - v1.30.10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: "${{ env.HELM_VERSION }}"

      - uses: actions/setup-python@v5
        with:
          python-version: "${{ env.PYTHON_VERSION }}"
          check-latest: true

      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@v1.12.0
        with:
          node_image: kindest/node:${{ matrix.k8s }}

      - name: Check K8s nodes
        run: |
          kubectl get nodes;

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

  release:
    needs: test-install-chart
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"